prompt_protection:
  enabled: true
  model: "gpt-3.5-turbo"
  max_tokens: 150
  temperature: 0.7
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  prompt_protection_rules:
    - rule_id: "1"
      description: "Prevent sensitive information leakage"
      action: "redact"
      keywords:
        - "password"
        - "credit card"
        - "social security"
    - rule_id: "2"
      description: "Limit inappropriate content"
      action: "block"
      keywords:
        - "violence"
        - "hate speech"
        - "adult content"
    - rule_id: "3"
      description: "Ensure compliance with regulations"
      action: "alert"
      regulations:
        - "GDPR"
        - "HIPAA"
        - "CCPA"
  logging:
    enabled: true
    log_level: "info"
    log_file: "guardrailsai_prompt_protection.log"